version: "3.7"
services:
    oasip-frontend:
        container_name: oasip-frontend
        build:
            context: .
            dockerfile: ./Dockerfile
        networks:
            - oasip-network
        environment:
            TZ: "Asia/Bangkok"

networks:
    oasip-network:
        external:
            name: oasip-network
